# @author: Bin Lee
# @email: blee@healthcompass.cloud

# ── Stage 1: install dependencies ───────────────────────────────────────────
FROM node:22-alpine AS deps
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

# ── Stage 2: build ───────────────────────────────────────────────────────────
FROM node:22-alpine AS builder
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time public env vars must be present at build time
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_MASSHEALTH_FORMS_BASE_URL
ARG NEXT_PUBLIC_MASSHEALTH_ANALYSIS_BASE_URL
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_ENABLED
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_CLIENT_TOKEN
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_APPLICATION_ID
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_SITE
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_SERVICE
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_ENV
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_VERSION
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_ORG
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_INSECURE_HTTP
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_API_VERSION
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_SAMPLE_RATE
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_REPLAY_SAMPLE_RATE
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_REPLAY_ENABLED
ARG NEXT_PUBLIC_OPENOBSERVE_RUM_PRIVACY_LEVEL

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_MASSHEALTH_FORMS_BASE_URL=$NEXT_PUBLIC_MASSHEALTH_FORMS_BASE_URL
ENV NEXT_PUBLIC_MASSHEALTH_ANALYSIS_BASE_URL=$NEXT_PUBLIC_MASSHEALTH_ANALYSIS_BASE_URL
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_ENABLED=$NEXT_PUBLIC_OPENOBSERVE_RUM_ENABLED
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_CLIENT_TOKEN=$NEXT_PUBLIC_OPENOBSERVE_RUM_CLIENT_TOKEN
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_APPLICATION_ID=$NEXT_PUBLIC_OPENOBSERVE_RUM_APPLICATION_ID
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_SITE=$NEXT_PUBLIC_OPENOBSERVE_RUM_SITE
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_SERVICE=$NEXT_PUBLIC_OPENOBSERVE_RUM_SERVICE
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_ENV=$NEXT_PUBLIC_OPENOBSERVE_RUM_ENV
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_VERSION=$NEXT_PUBLIC_OPENOBSERVE_RUM_VERSION
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_ORG=$NEXT_PUBLIC_OPENOBSERVE_RUM_ORG
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_INSECURE_HTTP=$NEXT_PUBLIC_OPENOBSERVE_RUM_INSECURE_HTTP
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_API_VERSION=$NEXT_PUBLIC_OPENOBSERVE_RUM_API_VERSION
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_SAMPLE_RATE=$NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_SAMPLE_RATE
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_REPLAY_SAMPLE_RATE=$NEXT_PUBLIC_OPENOBSERVE_RUM_REPLAY_SAMPLE_RATE
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_REPLAY_ENABLED=$NEXT_PUBLIC_OPENOBSERVE_RUM_SESSION_REPLAY_ENABLED
ENV NEXT_PUBLIC_OPENOBSERVE_RUM_PRIVACY_LEVEL=$NEXT_PUBLIC_OPENOBSERVE_RUM_PRIVACY_LEVEL

# Disable Next.js telemetry during build
ENV CI=true
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm build

# ── Stage 3: production runner ───────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy standalone output + static assets
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static   ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public          ./public

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
