// lib/glossary/seed-terms.ts

import type { GlossaryCategory } from './types'

interface SeedTerm {
  slug: string
  term_en: string
  definition_en: string
  definition_es: string
  category: GlossaryCategory
  aliases: string[]
  related_slugs: string[]
}

export const SEED_TERMS: SeedTerm[] = [
  // ── MassHealth Programs ──────────────────────────────────────────────────
  {
    slug: 'masshealth-standard',
    term_en: 'MassHealth Standard',
    definition_en: 'The most comprehensive MassHealth plan, available to children, young adults, parents, caretaker relatives, pregnant women, and people with disabilities. It covers a broad range of services including doctor visits, hospital care, prescriptions, mental health, and dental care at little or no cost.',
    definition_es: 'El plan de MassHealth más completo, disponible para niños, adultos jóvenes, padres, parientes cuidadores, mujeres embarazadas y personas con discapacidades. Cubre una amplia gama de servicios incluyendo visitas al médico, atención hospitalaria, recetas, salud mental y cuidado dental a poco o ningún costo.',
    category: 'program',
    aliases: ['MassHealth Standard coverage'],
    related_slugs: ['masshealth-careplus', 'masshealth-family-assistance'],
  },
  {
    slug: 'masshealth-careplus',
    term_en: 'MassHealth CarePlus',
    definition_en: 'A MassHealth plan for adults aged 19–64 who do not qualify for MassHealth Standard. It provides managed care coverage through a health plan and covers most medical services, though with a narrower benefit set than MassHealth Standard.',
    definition_es: 'Un plan de MassHealth para adultos de 19 a 64 años que no califican para MassHealth Standard. Brinda cobertura de atención administrada a través de un plan de salud y cubre la mayoría de los servicios médicos.',
    category: 'program',
    aliases: ['CarePlus'],
    related_slugs: ['masshealth-standard', 'connectorcare'],
  },
  {
    slug: 'masshealth-family-assistance',
    term_en: 'MassHealth Family Assistance',
    definition_en: 'A MassHealth program that helps pay for private health insurance premiums for people who do not qualify for full MassHealth coverage. It can help with employer-sponsored insurance or ConnectorCare plans.',
    definition_es: 'Un programa de MassHealth que ayuda a pagar las primas de seguro de salud privado para personas que no califican para la cobertura completa de MassHealth.',
    category: 'program',
    aliases: ['Family Assistance', 'MH Family Assistance'],
    related_slugs: ['connectorcare', 'premium-assistance'],
  },
  {
    slug: 'connectorcare',
    term_en: 'ConnectorCare',
    definition_en: 'A subsidized health insurance program through the Massachusetts Health Connector for people who earn too much for MassHealth but still need help affording coverage. Premiums and cost-sharing are reduced based on income, and plans are offered through the Connector marketplace.',
    definition_es: 'Un programa de seguro de salud subsidiado a través del Conector de Salud de Massachusetts para personas que ganan demasiado para MassHealth pero aún necesitan ayuda para costear la cobertura.',
    category: 'program',
    aliases: ['Connector Care'],
    related_slugs: ['masshealth-family-assistance', 'aptc', 'health-insurance-marketplace'],
  },
  {
    slug: 'health-safety-net',
    term_en: 'Health Safety Net',
    definition_en: 'A Massachusetts program that pays for certain hospital and community health center services for residents who are uninsured or underinsured. It is not insurance — it covers specific services for people who meet income and residency requirements.',
    definition_es: 'Un programa de Massachusetts que paga ciertos servicios hospitalarios y de centros de salud comunitaria para residentes sin seguro o con seguro insuficiente.',
    category: 'program',
    aliases: ['HSN', 'Safety Net'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'cmsp',
    term_en: "Children's Medical Security Plan",
    definition_en: "Massachusetts' program providing basic health coverage for uninsured children under 19 who do not qualify for MassHealth. It covers preventive care, sick visits, and some prescriptions at low or no cost.",
    definition_es: 'El programa de Massachusetts que brinda cobertura básica de salud para niños menores de 19 años sin seguro que no califican para MassHealth.',
    category: 'program',
    aliases: ['CMSP', 'Childrens Medical Security Plan'],
    related_slugs: ['masshealth-standard', 'chip'],
  },
  {
    slug: 'masshealth-commonhealth',
    term_en: 'MassHealth CommonHealth',
    definition_en: 'A MassHealth program for people with disabilities who do not qualify for other MassHealth programs, including working adults with disabilities. Enrollees may pay a premium based on income, but gain access to the full range of MassHealth benefits.',
    definition_es: 'Un programa de MassHealth para personas con discapacidades que no califican para otros programas de MassHealth, incluidos los adultos trabajadores con discapacidades.',
    category: 'program',
    aliases: ['CommonHealth'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'premium-assistance',
    term_en: 'Premium Assistance',
    definition_en: 'A benefit through MassHealth Family Assistance that helps pay your employer-sponsored health insurance premium. If your employer offers coverage and MassHealth determines it is cost-effective, MassHealth may contribute toward your monthly premium.',
    definition_es: 'Un beneficio a través de MassHealth Family Assistance que ayuda a pagar la prima de su seguro de salud patrocinado por el empleador.',
    category: 'program',
    aliases: [],
    related_slugs: ['masshealth-family-assistance', 'premium'],
  },
  // ── Insurance Concepts ───────────────────────────────────────────────────
  {
    slug: 'deductible',
    term_en: 'Deductible',
    definition_en: 'The amount you pay for covered health care services before your insurance plan starts to pay. For example, with a $1,000 deductible, you pay the first $1,000 of covered services yourself. After meeting your deductible, you usually pay a copayment or coinsurance for covered services.',
    definition_es: 'El monto que usted paga por los servicios de atención médica cubiertos antes de que su plan de seguro comience a pagar.',
    category: 'insurance',
    aliases: [],
    related_slugs: ['copayment', 'coinsurance', 'out-of-pocket-maximum'],
  },
  {
    slug: 'copayment',
    term_en: 'Copayment',
    definition_en: 'A fixed amount you pay for a covered health care service, usually at the time of the visit. For example, you might pay a $20 copay to see your primary care doctor. Copays typically do not count toward your deductible.',
    definition_es: 'Una cantidad fija que usted paga por un servicio de atención médica cubierto, generalmente en el momento de la visita.',
    category: 'insurance',
    aliases: ['co-pay', 'copay', 'co-payment'],
    related_slugs: ['deductible', 'coinsurance'],
  },
  {
    slug: 'coinsurance',
    term_en: 'Coinsurance',
    definition_en: 'Your share of the cost of a covered health care service, calculated as a percentage of the allowed amount. For example, if your coinsurance is 20%, you pay 20% and your insurance pays 80% after your deductible is met.',
    definition_es: 'Su parte del costo de un servicio de atención médica cubierto, calculada como un porcentaje del monto permitido.',
    category: 'insurance',
    aliases: ['co-insurance'],
    related_slugs: ['deductible', 'copayment', 'out-of-pocket-maximum'],
  },
  {
    slug: 'out-of-pocket-maximum',
    term_en: 'Out-of-Pocket Maximum',
    definition_en: 'The most you have to pay for covered services in a plan year. After reaching this amount, your insurance pays 100% of covered benefits. This limit includes your deductible, copayments, and coinsurance, but not your monthly premiums.',
    definition_es: 'El máximo que tiene que pagar por los servicios cubiertos en un año del plan. Después de alcanzar este monto, su seguro paga el 100% de los beneficios cubiertos.',
    category: 'insurance',
    aliases: ['out-of-pocket limit', 'OOP maximum', 'OOPM'],
    related_slugs: ['deductible', 'copayment', 'coinsurance'],
  },
  {
    slug: 'premium',
    term_en: 'Premium',
    definition_en: 'The amount you pay for your health insurance each month, regardless of whether you use any health care services. Premiums are separate from your deductible, copays, and coinsurance.',
    definition_es: 'El monto que paga por su seguro de salud cada mes, independientemente de si utiliza algún servicio de atención médica.',
    category: 'insurance',
    aliases: ['monthly premium', 'insurance premium'],
    related_slugs: ['deductible', 'aptc'],
  },
  {
    slug: 'in-network',
    term_en: 'In-Network',
    definition_en: 'Providers and facilities that have contracts with your health insurance plan to provide services at pre-negotiated rates. Using in-network providers almost always costs you less than going out-of-network.',
    definition_es: 'Proveedores e instalaciones que tienen contratos con su plan de seguro de salud para brindar servicios a tarifas negociadas previamente.',
    category: 'insurance',
    aliases: ['in network', 'out-of-network', 'out of network', 'network provider', 'network'],
    related_slugs: ['prior-authorization'],
  },
  {
    slug: 'prior-authorization',
    term_en: 'Prior Authorization',
    definition_en: 'Approval that your health insurance plan requires before you receive certain medications or services in order for them to be covered. Without prior authorization, your plan may not pay for the service even if it is generally covered.',
    definition_es: 'La aprobación que su plan de seguro de salud requiere antes de que reciba ciertos medicamentos o servicios para que sean cubiertos.',
    category: 'insurance',
    aliases: ['prior auth', 'pre-authorization', 'pre-auth', 'PA'],
    related_slugs: ['formulary'],
  },
  {
    slug: 'eob',
    term_en: 'Explanation of Benefits',
    definition_en: 'A statement from your insurance company showing what was billed for a medical service, what the insurance paid, and what you owe. An EOB is not a bill — it is a summary of how a claim was processed.',
    definition_es: 'Un estado de cuenta de su compañía de seguros que muestra lo que se facturó por un servicio médico, lo que pagó el seguro y lo que usted debe.',
    category: 'insurance',
    aliases: ['EOB', 'Explanation of Benefit'],
    related_slugs: ['copayment', 'coinsurance'],
  },
  {
    slug: 'formulary',
    term_en: 'Formulary',
    definition_en: 'A list of prescription drugs covered by your health insurance plan. Drugs on the formulary are grouped into tiers — lower tiers usually have lower cost-sharing. If your drug is not on the formulary, you may need prior authorization or pay full price.',
    definition_es: 'Una lista de medicamentos recetados cubiertos por su plan de seguro de salud.',
    category: 'insurance',
    aliases: ['drug formulary', 'covered drug list'],
    related_slugs: ['prior-authorization', 'step-therapy'],
  },
  {
    slug: 'coordination-of-benefits',
    term_en: 'Coordination of Benefits',
    definition_en: 'The process used when you are covered by more than one health insurance plan to determine which plan pays first (the primary insurer) and which pays second (the secondary insurer). It prevents double payment for the same service.',
    definition_es: 'El proceso utilizado cuando está cubierto por más de un plan de seguro de salud para determinar qué plan paga primero.',
    category: 'insurance',
    aliases: ['COB'],
    related_slugs: ['eob'],
  },
  // ── ACA / Enrollment ─────────────────────────────────────────────────────
  {
    slug: 'open-enrollment',
    term_en: 'Open Enrollment',
    definition_en: 'A set period each year — typically November 1 through January 15 in Massachusetts — when you can sign up for, change, or drop your health insurance plan. Outside of open enrollment, you generally can only make changes if you have a qualifying life event.',
    definition_es: 'Un período establecido cada año, generalmente del 1 de noviembre al 15 de enero en Massachusetts, cuando puede inscribirse, cambiar o abandonar su plan de seguro de salud.',
    category: 'aca',
    aliases: ['open enrollment period', 'OEP'],
    related_slugs: ['special-enrollment-period', 'qualifying-life-event'],
  },
  {
    slug: 'special-enrollment-period',
    term_en: 'Special Enrollment Period',
    definition_en: 'A time outside of Open Enrollment when you can sign up for or change your health coverage due to a qualifying life event such as losing other coverage, getting married, having a baby, or moving.',
    definition_es: 'Un período fuera de la inscripción abierta cuando puede inscribirse o cambiar su cobertura de salud debido a un evento de vida calificado.',
    category: 'aca',
    aliases: ['SEP', 'special enrollment'],
    related_slugs: ['open-enrollment', 'qualifying-life-event'],
  },
  {
    slug: 'qualifying-life-event',
    term_en: 'Qualifying Life Event',
    definition_en: 'A change in your situation — such as losing health coverage, moving, getting married, having a baby, or changes in income — that makes you eligible to enroll in or change your health plan outside of Open Enrollment.',
    definition_es: 'Un cambio en su situación, como perder cobertura médica, mudarse, casarse, tener un bebé o cambios en los ingresos, que le permite inscribirse en un plan de salud fuera de la inscripción abierta.',
    category: 'aca',
    aliases: ['QLE', 'life event', 'qualifying event'],
    related_slugs: ['special-enrollment-period'],
  },
  {
    slug: 'aptc',
    term_en: 'Advance Premium Tax Credit',
    definition_en: 'A federal tax credit that lowers your monthly health insurance premium if you buy coverage through the Health Connector and your income falls between 100% and 400% of the Federal Poverty Level. The credit is paid directly to your insurance company to reduce your monthly premium.',
    definition_es: 'Un crédito fiscal federal que reduce su prima mensual de seguro de salud si compra cobertura a través del Conector de Salud y sus ingresos están entre el 100% y el 400% del nivel federal de pobreza.',
    category: 'aca',
    aliases: ['APTC', 'premium tax credit', 'PTC', 'tax credit'],
    related_slugs: ['connectorcare', 'csr', 'fpl'],
  },
  {
    slug: 'csr',
    term_en: 'Cost-Sharing Reduction',
    definition_en: 'A discount that lowers the amount you pay for deductibles, copayments, and coinsurance when you get care. To qualify, you must enroll in a Silver plan through the Health Connector and have income between 100% and 250% of the Federal Poverty Level.',
    definition_es: 'Un descuento que reduce el monto que paga por deducibles, copagos y coseguro cuando recibe atención. Para calificar, debe inscribirse en un plan Silver.',
    category: 'aca',
    aliases: ['CSR', 'cost sharing reduction'],
    related_slugs: ['aptc', 'fpl'],
  },
  {
    slug: 'metal-tiers',
    term_en: 'Metal Tiers',
    definition_en: 'Health plans sold through the Marketplace are categorized into four metal levels — Bronze, Silver, Gold, and Platinum — based on how you and your plan share costs. Bronze plans have lower premiums but higher out-of-pocket costs; Platinum plans have higher premiums but lower costs when you use care.',
    definition_es: 'Los planes de salud se clasifican en cuatro niveles de metal: Bronze, Silver, Gold y Platinum, según cómo usted y su plan comparten los costos.',
    category: 'aca',
    aliases: ['Bronze', 'Silver', 'Gold', 'Platinum', 'plan tier', 'metal level'],
    related_slugs: ['csr', 'deductible'],
  },
  {
    slug: 'health-insurance-marketplace',
    term_en: 'Health Insurance Marketplace',
    definition_en: 'In Massachusetts, this is the Health Connector — the state exchange where individuals and families can shop for and enroll in health insurance plans. Financial assistance such as tax credits and cost-sharing reductions is available only through the Marketplace.',
    definition_es: 'En Massachusetts, este es el Conector de Salud, el intercambio estatal donde las personas y familias pueden comparar e inscribirse en planes de seguro de salud.',
    category: 'aca',
    aliases: ['Marketplace', 'Health Connector', 'Massachusetts Health Connector', 'exchange'],
    related_slugs: ['connectorcare', 'aptc', 'open-enrollment'],
  },
  {
    slug: 'chip',
    term_en: 'CHIP',
    definition_en: "The Children's Health Insurance Program provides low-cost health coverage to children in families that earn too much to qualify for Medicaid but cannot afford private insurance. In Massachusetts, CHIP is administered through MassHealth.",
    definition_es: 'El Programa de Seguro de Salud para Niños brinda cobertura de salud de bajo costo a niños en familias que ganan demasiado para calificar para Medicaid pero no pueden pagar un seguro privado.',
    category: 'aca',
    aliases: ["Children's Health Insurance Program"],
    related_slugs: ['cmsp', 'masshealth-standard'],
  },
  {
    slug: 'medicaid',
    term_en: 'Medicaid',
    definition_en: 'A joint federal and state program that provides free or low-cost health coverage to millions of Americans, including some low-income adults, children, pregnant women, elderly adults, and people with disabilities. In Massachusetts, Medicaid is called MassHealth.',
    definition_es: 'Un programa federal y estatal conjunto que brinda cobertura médica gratuita o de bajo costo a millones de estadounidenses. En Massachusetts, Medicaid se llama MassHealth.',
    category: 'aca',
    aliases: [],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'fpl',
    term_en: 'Federal Poverty Level',
    definition_en: 'A measure of income issued annually by the federal government, used to determine eligibility for many health coverage programs and financial assistance. For example, a family of four earning up to 138% FPL may qualify for MassHealth; between 139–400% FPL they may qualify for ConnectorCare subsidies.',
    definition_es: 'Una medida de ingresos emitida anualmente por el gobierno federal, utilizada para determinar la elegibilidad para muchos programas de cobertura de salud.',
    category: 'aca',
    aliases: ['FPL', 'poverty level', 'federal poverty guideline'],
    related_slugs: ['aptc', 'csr', 'masshealth-standard'],
  },
  {
    slug: 'minimum-essential-coverage',
    term_en: 'Minimum Essential Coverage',
    definition_en: 'The type of health coverage you must have under the Affordable Care Act to avoid a tax penalty (where applicable). MassHealth, employer-sponsored insurance, Medicare, and Marketplace plans all qualify. Coverage that does not meet this standard includes limited-benefit or short-term plans.',
    definition_es: 'El tipo de cobertura de salud que debe tener según la Ley del Cuidado de Salud a Bajo Precio para evitar una penalización fiscal.',
    category: 'aca',
    aliases: ['MEC', 'minimum coverage'],
    related_slugs: ['health-insurance-marketplace'],
  },
  {
    slug: 'catastrophic-plan',
    term_en: 'Catastrophic Plan',
    definition_en: 'A low-premium, high-deductible health plan available through the Marketplace to people under 30 or those with a hardship exemption. It covers three primary care visits per year before the deductible and protects against very high medical costs.',
    definition_es: 'Un plan de salud con prima baja y deducible alto disponible a través del Mercado para personas menores de 30 años o con una exención por dificultades.',
    category: 'aca',
    aliases: ['catastrophic coverage', 'catastrophic health plan'],
    related_slugs: ['deductible', 'metal-tiers'],
  },
  // ── Medical / Benefits ───────────────────────────────────────────────────
  {
    slug: 'pcp',
    term_en: 'Primary Care Provider',
    definition_en: 'Your main health care doctor — a general practitioner, family doctor, internist, or pediatrician — who provides routine care, manages chronic conditions, and refers you to specialists when needed. Many health plans require you to choose a PCP.',
    definition_es: 'Su médico principal de atención médica, que brinda atención de rutina, maneja condiciones crónicas y lo deriva a especialistas cuando es necesario.',
    category: 'medical',
    aliases: ['PCP', 'primary care doctor', 'primary care physician'],
    related_slugs: ['referral', 'specialist'],
  },
  {
    slug: 'referral',
    term_en: 'Referral',
    definition_en: 'A written order from your primary care provider allowing you to see a specialist or receive certain health services. Some health plans require a referral before covering specialist visits; others (PPOs) do not.',
    definition_es: 'Una orden escrita de su médico de atención primaria que le permite ver a un especialista o recibir ciertos servicios de salud.',
    category: 'medical',
    aliases: [],
    related_slugs: ['pcp', 'specialist', 'prior-authorization'],
  },
  {
    slug: 'specialist',
    term_en: 'Specialist',
    definition_en: 'A doctor who focuses on a specific area of medicine, such as cardiology, dermatology, or oncology. Visiting a specialist often costs more than seeing your primary care provider, and some plans require a referral first.',
    definition_es: 'Un médico que se enfoca en un área específica de la medicina, como cardiología, dermatología u oncología.',
    category: 'medical',
    aliases: [],
    related_slugs: ['pcp', 'referral'],
  },
  {
    slug: 'emergency-care',
    term_en: 'Emergency Care',
    definition_en: 'Medical treatment for a sudden, serious, or life-threatening condition that cannot wait for a regular appointment — such as chest pain, difficulty breathing, or severe injury. Emergency care is covered by most plans even if the hospital is out-of-network.',
    definition_es: 'Tratamiento médico para una condición repentina, grave o que pone en peligro la vida que no puede esperar una cita regular.',
    category: 'medical',
    aliases: ['emergency room', 'ER', 'urgent care', 'emergency department'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'dme',
    term_en: 'Durable Medical Equipment',
    definition_en: 'Equipment prescribed by a doctor for home use to help with a medical condition, such as wheelchairs, walkers, blood glucose monitors, or CPAP machines. Most health plans cover DME with a prescription, though prior authorization may be required.',
    definition_es: 'Equipo recetado por un médico para uso doméstico para ayudar con una condición médica, como sillas de ruedas, andadores, monitores de glucosa en sangre o máquinas CPAP.',
    category: 'medical',
    aliases: ['DME', 'durable equipment', 'medical equipment'],
    related_slugs: ['prior-authorization'],
  },
  {
    slug: 'mental-health-parity',
    term_en: 'Mental Health Parity',
    definition_en: 'A legal requirement that health plans cover mental health and substance use disorder benefits on the same level as medical and surgical benefits. This means your plan cannot impose stricter limits on mental health visits than on physical health visits.',
    definition_es: 'Un requisito legal de que los planes de salud cubran los beneficios de salud mental y trastornos por uso de sustancias al mismo nivel que los beneficios médicos y quirúrgicos.',
    category: 'medical',
    aliases: ['parity', 'mental health coverage'],
    related_slugs: [],
  },
  {
    slug: 'preventive-care',
    term_en: 'Preventive Care',
    definition_en: 'Routine health care — including screenings, check-ups, and counseling — aimed at preventing illness or detecting problems early. Under the ACA, most health plans must cover preventive services without charging a copay or deductible.',
    definition_es: 'Atención médica de rutina, incluidas pruebas de detección, controles y asesoramiento, destinada a prevenir enfermedades o detectar problemas temprano.',
    category: 'medical',
    aliases: ['preventative care', 'wellness visit', 'annual physical'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'telehealth',
    term_en: 'Telehealth',
    definition_en: 'Health care services delivered remotely using phone, video, or an online portal, without requiring you to visit a clinic in person. Telehealth is covered by most insurance plans and MassHealth for many types of visits.',
    definition_es: 'Servicios de atención médica brindados de forma remota mediante teléfono, video o un portal en línea, sin requerir que visite una clínica en persona.',
    category: 'medical',
    aliases: ['telemedicine', 'virtual care', 'virtual visit', 'video visit'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'step-therapy',
    term_en: 'Step Therapy',
    definition_en: 'A cost-control practice where your insurance plan requires you to try one or more lower-cost drugs first before approving coverage for a more expensive medication. If the first-line drugs do not work, you can appeal to get the preferred drug covered.',
    definition_es: 'Una práctica de control de costos donde su plan de seguro requiere que pruebe uno o más medicamentos de menor costo antes de aprobar la cobertura de un medicamento más costoso.',
    category: 'medical',
    aliases: ['fail-first', 'step protocol'],
    related_slugs: ['formulary', 'prior-authorization'],
  },
  {
    slug: 'preexisting-condition',
    term_en: 'Preexisting Condition',
    definition_en: 'A health problem you had before your new health coverage started, such as asthma, diabetes, or cancer. Under the ACA, health plans cannot deny coverage or charge more because of preexisting conditions.',
    definition_es: 'Un problema de salud que tenía antes de que comenzara su nueva cobertura de salud. Según la ACA, los planes de salud no pueden negar cobertura ni cobrar más debido a condiciones preexistentes.',
    category: 'medical',
    aliases: ['pre-existing condition', 'preexisting health condition'],
    related_slugs: ['minimum-essential-coverage'],
  },
  {
    slug: 'cobra',
    term_en: 'COBRA',
    definition_en: 'A federal law that lets you keep your employer-sponsored health insurance for a limited time after leaving your job, losing hours, or experiencing another qualifying event. You pay the full premium yourself — no employer contribution — which makes COBRA significantly more expensive than coverage while employed.',
    definition_es: 'Una ley federal que le permite mantener su seguro de salud patrocinado por el empleador por un tiempo limitado después de dejar su trabajo.',
    category: 'medical',
    aliases: ['COBRA coverage', 'continuation coverage'],
    related_slugs: ['qualifying-life-event', 'premium'],
  },
  {
    slug: 'appeal',
    term_en: 'Appeal',
    definition_en: 'A formal request for your health insurance company or MassHealth to review and reverse a decision to deny, reduce, or stop coverage or payment for a health care service. You generally have a right to appeal any denial, and you can request an independent external review if the internal appeal is denied.',
    definition_es: 'Una solicitud formal para que su compañía de seguro de salud o MassHealth revise y revierta una decisión de denegar, reducir o detener la cobertura.',
    category: 'medical',
    aliases: ['insurance appeal', 'coverage appeal'],
    related_slugs: ['grievance', 'redetermination'],
  },
  {
    slug: 'grievance',
    term_en: 'Grievance',
    definition_en: 'A complaint you make to your health plan about the quality of care or services you received, as opposed to a coverage denial (which is an appeal). You can file a grievance if you are unhappy with wait times, provider behavior, or how a claim was handled.',
    definition_es: 'Una queja que presenta a su plan de salud sobre la calidad de la atención o los servicios recibidos.',
    category: 'medical',
    aliases: ['complaint', 'health plan complaint'],
    related_slugs: ['appeal'],
  },
  {
    slug: 'redetermination',
    term_en: 'Redetermination',
    definition_en: 'The process by which MassHealth reviews your eligibility for benefits, either periodically (annual renewal) or after a change in your circumstances such as a change in income or household size. Also used to describe a first-level appeal of a MassHealth decision.',
    definition_es: 'El proceso mediante el cual MassHealth revisa su elegibilidad para beneficios, ya sea periódicamente o después de un cambio en sus circunstancias.',
    category: 'medical',
    aliases: ['MassHealth redetermination'],
    related_slugs: ['appeal', 'open-enrollment'],
  },
  {
    slug: 'retroactive-coverage',
    term_en: 'Retroactive Coverage',
    definition_en: 'Health insurance coverage that is approved to start before the date your application was processed. MassHealth may grant retroactive coverage for up to three months before your application date if you had qualifying medical expenses during that period.',
    definition_es: 'Cobertura de seguro de salud que se aprueba para comenzar antes de la fecha en que se procesó su solicitud.',
    category: 'medical',
    aliases: ['retro coverage', 'back-dated coverage'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'ltss',
    term_en: 'Long-Term Services and Supports',
    definition_en: 'A range of health and social services for people who need help with daily activities over an extended period due to aging, disability, or chronic illness. Examples include personal care attendant services, adult day health, and home health aides. MassHealth covers LTSS for eligible members.',
    definition_es: 'Una variedad de servicios de salud y sociales para personas que necesitan ayuda con las actividades diarias durante un período prolongado debido al envejecimiento, discapacidad o enfermedad crónica.',
    category: 'medical',
    aliases: ['LTSS', 'long-term care', 'long term services'],
    related_slugs: ['masshealth-standard'],
  },
]
