// lib/glossary/seed-terms.ts

import type { GlossaryCategory } from './types'

interface SeedTerm {
  slug: string
  term_en: string
  definition_en: string
  definition_es: string
  category: GlossaryCategory
  aliases: string[]
  related_slugs: string[]
}

export const SEED_TERMS: SeedTerm[] = [
  // ── MassHealth Programs ──────────────────────────────────────────────────
  {
    slug: 'masshealth-standard',
    term_en: 'MassHealth Standard',
    definition_en: 'The most comprehensive MassHealth plan, available to children, young adults, parents, caretaker relatives, pregnant women, and people with disabilities. It covers a broad range of services including doctor visits, hospital care, prescriptions, mental health, and dental care at little or no cost.',
    definition_es: 'El plan de MassHealth más completo, disponible para niños, adultos jóvenes, padres, parientes cuidadores, mujeres embarazadas y personas con discapacidades. Cubre una amplia gama de servicios incluyendo visitas al médico, atención hospitalaria, recetas, salud mental y cuidado dental a poco o ningún costo.',
    category: 'program',
    aliases: ['MassHealth Standard coverage'],
    related_slugs: ['masshealth-careplus', 'masshealth-family-assistance'],
  },
  {
    slug: 'masshealth-careplus',
    term_en: 'MassHealth CarePlus',
    definition_en: 'A MassHealth plan for adults aged 19–64 who do not qualify for MassHealth Standard. It provides managed care coverage through a health plan and covers most medical services, though with a narrower benefit set than MassHealth Standard.',
    definition_es: 'Un plan de MassHealth para adultos de 19 a 64 años que no califican para MassHealth Standard. Brinda cobertura de atención administrada a través de un plan de salud y cubre la mayoría de los servicios médicos.',
    category: 'program',
    aliases: ['CarePlus'],
    related_slugs: ['masshealth-standard', 'connectorcare'],
  },
  {
    slug: 'masshealth-family-assistance',
    term_en: 'MassHealth Family Assistance',
    definition_en: 'A MassHealth program that helps pay for private health insurance premiums for people who do not qualify for full MassHealth coverage. It can help with employer-sponsored insurance or ConnectorCare plans.',
    definition_es: 'Un programa de MassHealth que ayuda a pagar las primas de seguro de salud privado para personas que no califican para la cobertura completa de MassHealth.',
    category: 'program',
    aliases: ['Family Assistance', 'MH Family Assistance'],
    related_slugs: ['connectorcare', 'premium-assistance'],
  },
  {
    slug: 'connectorcare',
    term_en: 'ConnectorCare',
    definition_en: 'A subsidized health insurance program through the Massachusetts Health Connector for people who earn too much for MassHealth but still need help affording coverage. Premiums and cost-sharing are reduced based on income, and plans are offered through the Connector marketplace.',
    definition_es: 'Un programa de seguro de salud subsidiado a través del Conector de Salud de Massachusetts para personas que ganan demasiado para MassHealth pero aún necesitan ayuda para costear la cobertura.',
    category: 'program',
    aliases: ['Connector Care'],
    related_slugs: ['masshealth-family-assistance', 'aptc', 'health-insurance-marketplace'],
  },
  {
    slug: 'health-safety-net',
    term_en: 'Health Safety Net',
    definition_en: 'A Massachusetts program that pays for certain hospital and community health center services for residents who are uninsured or underinsured. It is not insurance — it covers specific services for people who meet income and residency requirements.',
    definition_es: 'Un programa de Massachusetts que paga ciertos servicios hospitalarios y de centros de salud comunitaria para residentes sin seguro o con seguro insuficiente.',
    category: 'program',
    aliases: ['HSN', 'Safety Net'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'cmsp',
    term_en: "Children's Medical Security Plan",
    definition_en: "Massachusetts' program providing basic health coverage for uninsured children under 19 who do not qualify for MassHealth. It covers preventive care, sick visits, and some prescriptions at low or no cost.",
    definition_es: 'El programa de Massachusetts que brinda cobertura básica de salud para niños menores de 19 años sin seguro que no califican para MassHealth.',
    category: 'program',
    aliases: ['CMSP', 'Childrens Medical Security Plan'],
    related_slugs: ['masshealth-standard', 'chip'],
  },
  {
    slug: 'masshealth-commonhealth',
    term_en: 'MassHealth CommonHealth',
    definition_en: 'A MassHealth program for people with disabilities who do not qualify for other MassHealth programs, including working adults with disabilities. Enrollees may pay a premium based on income, but gain access to the full range of MassHealth benefits.',
    definition_es: 'Un programa de MassHealth para personas con discapacidades que no califican para otros programas de MassHealth, incluidos los adultos trabajadores con discapacidades.',
    category: 'program',
    aliases: ['CommonHealth'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'premium-assistance',
    term_en: 'Premium Assistance',
    definition_en: 'A benefit through MassHealth Family Assistance that helps pay your employer-sponsored health insurance premium. If your employer offers coverage and MassHealth determines it is cost-effective, MassHealth may contribute toward your monthly premium.',
    definition_es: 'Un beneficio a través de MassHealth Family Assistance que ayuda a pagar la prima de su seguro de salud patrocinado por el empleador.',
    category: 'program',
    aliases: [],
    related_slugs: ['masshealth-family-assistance', 'premium'],
  },
  // ── Insurance Concepts ───────────────────────────────────────────────────
  {
    slug: 'deductible',
    term_en: 'Deductible',
    definition_en: 'The amount you pay for covered health care services before your insurance plan starts to pay. For example, with a $1,000 deductible, you pay the first $1,000 of covered services yourself. After meeting your deductible, you usually pay a copayment or coinsurance for covered services.',
    definition_es: 'El monto que usted paga por los servicios de atención médica cubiertos antes de que su plan de seguro comience a pagar.',
    category: 'insurance',
    aliases: [],
    related_slugs: ['copayment', 'coinsurance', 'out-of-pocket-maximum'],
  },
  {
    slug: 'copayment',
    term_en: 'Copayment',
    definition_en: 'A fixed amount you pay for a covered health care service, usually at the time of the visit. For example, you might pay a $20 copay to see your primary care doctor. Copays typically do not count toward your deductible.',
    definition_es: 'Una cantidad fija que usted paga por un servicio de atención médica cubierto, generalmente en el momento de la visita.',
    category: 'insurance',
    aliases: ['co-pay', 'copay', 'co-payment'],
    related_slugs: ['deductible', 'coinsurance'],
  },
  {
    slug: 'coinsurance',
    term_en: 'Coinsurance',
    definition_en: 'Your share of the cost of a covered health care service, calculated as a percentage of the allowed amount. For example, if your coinsurance is 20%, you pay 20% and your insurance pays 80% after your deductible is met.',
    definition_es: 'Su parte del costo de un servicio de atención médica cubierto, calculada como un porcentaje del monto permitido.',
    category: 'insurance',
    aliases: ['co-insurance'],
    related_slugs: ['deductible', 'copayment', 'out-of-pocket-maximum'],
  },
  {
    slug: 'out-of-pocket-maximum',
    term_en: 'Out-of-Pocket Maximum',
    definition_en: 'The most you have to pay for covered services in a plan year. After reaching this amount, your insurance pays 100% of covered benefits. This limit includes your deductible, copayments, and coinsurance, but not your monthly premiums.',
    definition_es: 'El máximo que tiene que pagar por los servicios cubiertos en un año del plan. Después de alcanzar este monto, su seguro paga el 100% de los beneficios cubiertos.',
    category: 'insurance',
    aliases: ['out-of-pocket limit', 'OOP maximum', 'OOPM'],
    related_slugs: ['deductible', 'copayment', 'coinsurance'],
  },
  {
    slug: 'premium',
    term_en: 'Premium',
    definition_en: 'The amount you pay for your health insurance each month, regardless of whether you use any health care services. Premiums are separate from your deductible, copays, and coinsurance.',
    definition_es: 'El monto que paga por su seguro de salud cada mes, independientemente de si utiliza algún servicio de atención médica.',
    category: 'insurance',
    aliases: ['monthly premium', 'insurance premium'],
    related_slugs: ['deductible', 'aptc'],
  },
  {
    slug: 'in-network',
    term_en: 'In-Network',
    definition_en: 'Providers and facilities that have contracts with your health insurance plan to provide services at pre-negotiated rates. Using in-network providers almost always costs you less than going out-of-network.',
    definition_es: 'Proveedores e instalaciones que tienen contratos con su plan de seguro de salud para brindar servicios a tarifas negociadas previamente.',
    category: 'insurance',
    aliases: ['in network', 'out-of-network', 'out of network', 'network provider', 'network'],
    related_slugs: ['prior-authorization'],
  },
  {
    slug: 'prior-authorization',
    term_en: 'Prior Authorization',
    definition_en: 'Approval that your health insurance plan requires before you receive certain medications or services in order for them to be covered. Without prior authorization, your plan may not pay for the service even if it is generally covered.',
    definition_es: 'La aprobación que su plan de seguro de salud requiere antes de que reciba ciertos medicamentos o servicios para que sean cubiertos.',
    category: 'insurance',
    aliases: ['prior auth', 'pre-authorization', 'pre-auth', 'PA'],
    related_slugs: ['formulary'],
  },
  {
    slug: 'eob',
    term_en: 'Explanation of Benefits',
    definition_en: 'A statement from your insurance company showing what was billed for a medical service, what the insurance paid, and what you owe. An EOB is not a bill — it is a summary of how a claim was processed.',
    definition_es: 'Un estado de cuenta de su compañía de seguros que muestra lo que se facturó por un servicio médico, lo que pagó el seguro y lo que usted debe.',
    category: 'insurance',
    aliases: ['EOB', 'Explanation of Benefit'],
    related_slugs: ['copayment', 'coinsurance'],
  },
  {
    slug: 'formulary',
    term_en: 'Formulary',
    definition_en: 'A list of prescription drugs covered by your health insurance plan. Drugs on the formulary are grouped into tiers — lower tiers usually have lower cost-sharing. If your drug is not on the formulary, you may need prior authorization or pay full price.',
    definition_es: 'Una lista de medicamentos recetados cubiertos por su plan de seguro de salud.',
    category: 'insurance',
    aliases: ['drug formulary', 'covered drug list'],
    related_slugs: ['prior-authorization', 'step-therapy'],
  },
  {
    slug: 'coordination-of-benefits',
    term_en: 'Coordination of Benefits',
    definition_en: 'The process used when you are covered by more than one health insurance plan to determine which plan pays first (the primary insurer) and which pays second (the secondary insurer). It prevents double payment for the same service.',
    definition_es: 'El proceso utilizado cuando está cubierto por más de un plan de seguro de salud para determinar qué plan paga primero.',
    category: 'insurance',
    aliases: ['COB'],
    related_slugs: ['eob'],
  },
  // ── ACA / Enrollment ─────────────────────────────────────────────────────
  {
    slug: 'open-enrollment',
    term_en: 'Open Enrollment',
    definition_en: 'A set period each year — typically November 1 through January 15 in Massachusetts — when you can sign up for, change, or drop your health insurance plan. Outside of open enrollment, you generally can only make changes if you have a qualifying life event.',
    definition_es: 'Un período establecido cada año, generalmente del 1 de noviembre al 15 de enero en Massachusetts, cuando puede inscribirse, cambiar o abandonar su plan de seguro de salud.',
    category: 'aca',
    aliases: ['open enrollment period', 'OEP'],
    related_slugs: ['special-enrollment-period', 'qualifying-life-event'],
  },
  {
    slug: 'special-enrollment-period',
    term_en: 'Special Enrollment Period',
    definition_en: 'A time outside of Open Enrollment when you can sign up for or change your health coverage due to a qualifying life event such as losing other coverage, getting married, having a baby, or moving.',
    definition_es: 'Un período fuera de la inscripción abierta cuando puede inscribirse o cambiar su cobertura de salud debido a un evento de vida calificado.',
    category: 'aca',
    aliases: ['SEP', 'special enrollment'],
    related_slugs: ['open-enrollment', 'qualifying-life-event'],
  },
  {
    slug: 'qualifying-life-event',
    term_en: 'Qualifying Life Event',
    definition_en: 'A change in your situation — such as losing health coverage, moving, getting married, having a baby, or changes in income — that makes you eligible to enroll in or change your health plan outside of Open Enrollment.',
    definition_es: 'Un cambio en su situación, como perder cobertura médica, mudarse, casarse, tener un bebé o cambios en los ingresos, que le permite inscribirse en un plan de salud fuera de la inscripción abierta.',
    category: 'aca',
    aliases: ['QLE', 'life event', 'qualifying event'],
    related_slugs: ['special-enrollment-period'],
  },
  {
    slug: 'aptc',
    term_en: 'Advance Premium Tax Credit',
    definition_en: 'A federal tax credit that lowers your monthly health insurance premium if you buy coverage through the Health Connector and your income falls between 100% and 400% of the Federal Poverty Level. The credit is paid directly to your insurance company to reduce your monthly premium.',
    definition_es: 'Un crédito fiscal federal que reduce su prima mensual de seguro de salud si compra cobertura a través del Conector de Salud y sus ingresos están entre el 100% y el 400% del nivel federal de pobreza.',
    category: 'aca',
    aliases: ['APTC', 'premium tax credit', 'PTC', 'tax credit'],
    related_slugs: ['connectorcare', 'csr', 'fpl'],
  },
  {
    slug: 'csr',
    term_en: 'Cost-Sharing Reduction',
    definition_en: 'A discount that lowers the amount you pay for deductibles, copayments, and coinsurance when you get care. To qualify, you must enroll in a Silver plan through the Health Connector and have income between 100% and 250% of the Federal Poverty Level.',
    definition_es: 'Un descuento que reduce el monto que paga por deducibles, copagos y coseguro cuando recibe atención. Para calificar, debe inscribirse en un plan Silver.',
    category: 'aca',
    aliases: ['CSR', 'cost sharing reduction'],
    related_slugs: ['aptc', 'fpl'],
  },
  {
    slug: 'metal-tiers',
    term_en: 'Metal Tiers',
    definition_en: 'Health plans sold through the Marketplace are categorized into four metal levels — Bronze, Silver, Gold, and Platinum — based on how you and your plan share costs. Bronze plans have lower premiums but higher out-of-pocket costs; Platinum plans have higher premiums but lower costs when you use care.',
    definition_es: 'Los planes de salud se clasifican en cuatro niveles de metal: Bronze, Silver, Gold y Platinum, según cómo usted y su plan comparten los costos.',
    category: 'aca',
    aliases: ['Bronze', 'Silver', 'Gold', 'Platinum', 'plan tier', 'metal level'],
    related_slugs: ['csr', 'deductible'],
  },
  {
    slug: 'health-insurance-marketplace',
    term_en: 'Health Insurance Marketplace',
    definition_en: 'In Massachusetts, this is the Health Connector — the state exchange where individuals and families can shop for and enroll in health insurance plans. Financial assistance such as tax credits and cost-sharing reductions is available only through the Marketplace.',
    definition_es: 'En Massachusetts, este es el Conector de Salud, el intercambio estatal donde las personas y familias pueden comparar e inscribirse en planes de seguro de salud.',
    category: 'aca',
    aliases: ['Marketplace', 'Health Connector', 'Massachusetts Health Connector', 'exchange'],
    related_slugs: ['connectorcare', 'aptc', 'open-enrollment'],
  },
  {
    slug: 'chip',
    term_en: 'CHIP',
    definition_en: "The Children's Health Insurance Program provides low-cost health coverage to children in families that earn too much to qualify for Medicaid but cannot afford private insurance. In Massachusetts, CHIP is administered through MassHealth.",
    definition_es: 'El Programa de Seguro de Salud para Niños brinda cobertura de salud de bajo costo a niños en familias que ganan demasiado para calificar para Medicaid pero no pueden pagar un seguro privado.',
    category: 'aca',
    aliases: ["Children's Health Insurance Program"],
    related_slugs: ['cmsp', 'masshealth-standard'],
  },
  {
    slug: 'medicaid',
    term_en: 'Medicaid',
    definition_en: 'A joint federal and state program that provides free or low-cost health coverage to millions of Americans, including some low-income adults, children, pregnant women, elderly adults, and people with disabilities. In Massachusetts, Medicaid is called MassHealth.',
    definition_es: 'Un programa federal y estatal conjunto que brinda cobertura médica gratuita o de bajo costo a millones de estadounidenses. En Massachusetts, Medicaid se llama MassHealth.',
    category: 'aca',
    aliases: [],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'fpl',
    term_en: 'Federal Poverty Level',
    definition_en: 'A measure of income issued annually by the federal government, used to determine eligibility for many health coverage programs and financial assistance. For example, a family of four earning up to 138% FPL may qualify for MassHealth; between 139–400% FPL they may qualify for ConnectorCare subsidies.',
    definition_es: 'Una medida de ingresos emitida anualmente por el gobierno federal, utilizada para determinar la elegibilidad para muchos programas de cobertura de salud.',
    category: 'aca',
    aliases: ['FPL', 'poverty level', 'federal poverty guideline'],
    related_slugs: ['aptc', 'csr', 'masshealth-standard'],
  },
  {
    slug: 'minimum-essential-coverage',
    term_en: 'Minimum Essential Coverage',
    definition_en: 'The type of health coverage you must have under the Affordable Care Act to avoid a tax penalty (where applicable). MassHealth, employer-sponsored insurance, Medicare, and Marketplace plans all qualify. Coverage that does not meet this standard includes limited-benefit or short-term plans.',
    definition_es: 'El tipo de cobertura de salud que debe tener según la Ley del Cuidado de Salud a Bajo Precio para evitar una penalización fiscal.',
    category: 'aca',
    aliases: ['MEC', 'minimum coverage'],
    related_slugs: ['health-insurance-marketplace'],
  },
  {
    slug: 'catastrophic-plan',
    term_en: 'Catastrophic Plan',
    definition_en: 'A low-premium, high-deductible health plan available through the Marketplace to people under 30 or those with a hardship exemption. It covers three primary care visits per year before the deductible and protects against very high medical costs.',
    definition_es: 'Un plan de salud con prima baja y deducible alto disponible a través del Mercado para personas menores de 30 años o con una exención por dificultades.',
    category: 'aca',
    aliases: ['catastrophic coverage', 'catastrophic health plan'],
    related_slugs: ['deductible', 'metal-tiers'],
  },
  // ── Medical / Benefits ───────────────────────────────────────────────────
  {
    slug: 'pcp',
    term_en: 'Primary Care Provider',
    definition_en: 'Your main health care doctor — a general practitioner, family doctor, internist, or pediatrician — who provides routine care, manages chronic conditions, and refers you to specialists when needed. Many health plans require you to choose a PCP.',
    definition_es: 'Su médico principal de atención médica, que brinda atención de rutina, maneja condiciones crónicas y lo deriva a especialistas cuando es necesario.',
    category: 'medical',
    aliases: ['PCP', 'primary care doctor', 'primary care physician'],
    related_slugs: ['referral', 'specialist'],
  },
  {
    slug: 'referral',
    term_en: 'Referral',
    definition_en: 'A written order from your primary care provider allowing you to see a specialist or receive certain health services. Some health plans require a referral before covering specialist visits; others (PPOs) do not.',
    definition_es: 'Una orden escrita de su médico de atención primaria que le permite ver a un especialista o recibir ciertos servicios de salud.',
    category: 'medical',
    aliases: [],
    related_slugs: ['pcp', 'specialist', 'prior-authorization'],
  },
  {
    slug: 'specialist',
    term_en: 'Specialist',
    definition_en: 'A doctor who focuses on a specific area of medicine, such as cardiology, dermatology, or oncology. Visiting a specialist often costs more than seeing your primary care provider, and some plans require a referral first.',
    definition_es: 'Un médico que se enfoca en un área específica de la medicina, como cardiología, dermatología u oncología.',
    category: 'medical',
    aliases: [],
    related_slugs: ['pcp', 'referral'],
  },
  {
    slug: 'emergency-care',
    term_en: 'Emergency Care',
    definition_en: 'Medical treatment for a sudden, serious, or life-threatening condition that cannot wait for a regular appointment — such as chest pain, difficulty breathing, or severe injury. Emergency care is covered by most plans even if the hospital is out-of-network.',
    definition_es: 'Tratamiento médico para una condición repentina, grave o que pone en peligro la vida que no puede esperar una cita regular.',
    category: 'medical',
    aliases: ['emergency room', 'ER', 'urgent care', 'emergency department'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'dme',
    term_en: 'Durable Medical Equipment',
    definition_en: 'Equipment prescribed by a doctor for home use to help with a medical condition, such as wheelchairs, walkers, blood glucose monitors, or CPAP machines. Most health plans cover DME with a prescription, though prior authorization may be required.',
    definition_es: 'Equipo recetado por un médico para uso doméstico para ayudar con una condición médica, como sillas de ruedas, andadores, monitores de glucosa en sangre o máquinas CPAP.',
    category: 'medical',
    aliases: ['DME', 'durable equipment', 'medical equipment'],
    related_slugs: ['prior-authorization'],
  },
  {
    slug: 'mental-health-parity',
    term_en: 'Mental Health Parity',
    definition_en: 'A legal requirement that health plans cover mental health and substance use disorder benefits on the same level as medical and surgical benefits. This means your plan cannot impose stricter limits on mental health visits than on physical health visits.',
    definition_es: 'Un requisito legal de que los planes de salud cubran los beneficios de salud mental y trastornos por uso de sustancias al mismo nivel que los beneficios médicos y quirúrgicos.',
    category: 'medical',
    aliases: ['parity', 'mental health coverage'],
    related_slugs: [],
  },
  {
    slug: 'preventive-care',
    term_en: 'Preventive Care',
    definition_en: 'Routine health care — including screenings, check-ups, and counseling — aimed at preventing illness or detecting problems early. Under the ACA, most health plans must cover preventive services without charging a copay or deductible.',
    definition_es: 'Atención médica de rutina, incluidas pruebas de detección, controles y asesoramiento, destinada a prevenir enfermedades o detectar problemas temprano.',
    category: 'medical',
    aliases: ['preventative care', 'wellness visit', 'annual physical'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'telehealth',
    term_en: 'Telehealth',
    definition_en: 'Health care services delivered remotely using phone, video, or an online portal, without requiring you to visit a clinic in person. Telehealth is covered by most insurance plans and MassHealth for many types of visits.',
    definition_es: 'Servicios de atención médica brindados de forma remota mediante teléfono, video o un portal en línea, sin requerir que visite una clínica en persona.',
    category: 'medical',
    aliases: ['telemedicine', 'virtual care', 'virtual visit', 'video visit'],
    related_slugs: ['pcp'],
  },
  {
    slug: 'step-therapy',
    term_en: 'Step Therapy',
    definition_en: 'A cost-control practice where your insurance plan requires you to try one or more lower-cost drugs first before approving coverage for a more expensive medication. If the first-line drugs do not work, you can appeal to get the preferred drug covered.',
    definition_es: 'Una práctica de control de costos donde su plan de seguro requiere que pruebe uno o más medicamentos de menor costo antes de aprobar la cobertura de un medicamento más costoso.',
    category: 'medical',
    aliases: ['fail-first', 'step protocol'],
    related_slugs: ['formulary', 'prior-authorization'],
  },
  {
    slug: 'preexisting-condition',
    term_en: 'Preexisting Condition',
    definition_en: 'A health problem you had before your new health coverage started, such as asthma, diabetes, or cancer. Under the ACA, health plans cannot deny coverage or charge more because of preexisting conditions.',
    definition_es: 'Un problema de salud que tenía antes de que comenzara su nueva cobertura de salud. Según la ACA, los planes de salud no pueden negar cobertura ni cobrar más debido a condiciones preexistentes.',
    category: 'medical',
    aliases: ['pre-existing condition', 'preexisting health condition'],
    related_slugs: ['minimum-essential-coverage'],
  },
  {
    slug: 'cobra',
    term_en: 'COBRA',
    definition_en: 'A federal law that lets you keep your employer-sponsored health insurance for a limited time after leaving your job, losing hours, or experiencing another qualifying event. You pay the full premium yourself — no employer contribution — which makes COBRA significantly more expensive than coverage while employed.',
    definition_es: 'Una ley federal que le permite mantener su seguro de salud patrocinado por el empleador por un tiempo limitado después de dejar su trabajo.',
    category: 'medical',
    aliases: ['COBRA coverage', 'continuation coverage'],
    related_slugs: ['qualifying-life-event', 'premium'],
  },
  {
    slug: 'appeal',
    term_en: 'Appeal',
    definition_en: 'A formal request for your health insurance company or MassHealth to review and reverse a decision to deny, reduce, or stop coverage or payment for a health care service. You generally have a right to appeal any denial, and you can request an independent external review if the internal appeal is denied.',
    definition_es: 'Una solicitud formal para que su compañía de seguro de salud o MassHealth revise y revierta una decisión de denegar, reducir o detener la cobertura.',
    category: 'medical',
    aliases: ['insurance appeal', 'coverage appeal'],
    related_slugs: ['grievance', 'redetermination'],
  },
  {
    slug: 'grievance',
    term_en: 'Grievance',
    definition_en: 'A complaint you make to your health plan about the quality of care or services you received, as opposed to a coverage denial (which is an appeal). You can file a grievance if you are unhappy with wait times, provider behavior, or how a claim was handled.',
    definition_es: 'Una queja que presenta a su plan de salud sobre la calidad de la atención o los servicios recibidos.',
    category: 'medical',
    aliases: ['complaint', 'health plan complaint'],
    related_slugs: ['appeal'],
  },
  {
    slug: 'redetermination',
    term_en: 'Redetermination',
    definition_en: 'The process by which MassHealth reviews your eligibility for benefits, either periodically (annual renewal) or after a change in your circumstances such as a change in income or household size. Also used to describe a first-level appeal of a MassHealth decision.',
    definition_es: 'El proceso mediante el cual MassHealth revisa su elegibilidad para beneficios, ya sea periódicamente o después de un cambio en sus circunstancias.',
    category: 'medical',
    aliases: ['MassHealth redetermination'],
    related_slugs: ['appeal', 'open-enrollment'],
  },
  {
    slug: 'retroactive-coverage',
    term_en: 'Retroactive Coverage',
    definition_en: 'Health insurance coverage that is approved to start before the date your application was processed. MassHealth may grant retroactive coverage for up to three months before your application date if you had qualifying medical expenses during that period.',
    definition_es: 'Cobertura de seguro de salud que se aprueba para comenzar antes de la fecha en que se procesó su solicitud.',
    category: 'medical',
    aliases: ['retro coverage', 'back-dated coverage'],
    related_slugs: ['masshealth-standard'],
  },
  {
    slug: 'ltss',
    term_en: 'Long-Term Services and Supports',
    definition_en: 'A range of health and social services for people who need help with daily activities over an extended period due to aging, disability, or chronic illness. Examples include personal care attendant services, adult day health, and home health aides. MassHealth covers LTSS for eligible members.',
    definition_es: 'Una variedad de servicios de salud y sociales para personas que necesitan ayuda con las actividades diarias durante un período prolongado debido al envejecimiento, discapacidad o enfermedad crónica.',
    category: 'medical',
    aliases: ['LTSS', 'long-term care', 'long term services'],
    related_slugs: ['masshealth-standard', 'pca', 'home-health-care'],
  },

  // ── Medicare ─────────────────────────────────────────────────────────────
  {
    slug: 'medicare',
    term_en: 'Medicare',
    definition_en: 'The federal health insurance program primarily for people age 65 or older, and for certain younger people with disabilities or End-Stage Renal Disease. Medicare has four parts: Part A (hospital), Part B (medical), Part C (Medicare Advantage), and Part D (prescription drugs). Some MassHealth members are also enrolled in Medicare — they are called "dual eligible."',
    definition_es: 'El programa federal de seguro de salud principalmente para personas de 65 años o más, y para ciertas personas más jóvenes con discapacidades. Medicare tiene cuatro partes: Parte A (hospital), Parte B (médica), Parte C (Medicare Advantage) y Parte D (medicamentos).',
    category: 'program',
    aliases: ['Medicare coverage'],
    related_slugs: ['medicare-part-d', 'dual-eligible', 'masshealth-standard'],
  },
  {
    slug: 'medicare-part-d',
    term_en: 'Medicare Part D',
    definition_en: 'The part of Medicare that covers prescription drugs. Part D plans are offered by private insurers approved by Medicare. For MassHealth members who also have Medicare, MassHealth may help pay Part D premiums and cost-sharing through the Medicare Savings Program.',
    definition_es: 'La parte de Medicare que cubre medicamentos recetados. Los planes de la Parte D son ofrecidos por aseguradoras privadas aprobadas por Medicare.',
    category: 'program',
    aliases: ['Part D', 'Medicare drug coverage'],
    related_slugs: ['medicare', 'formulary'],
  },
  {
    slug: 'dual-eligible',
    term_en: 'Dual Eligible',
    definition_en: 'A person who qualifies for both Medicare and Medicaid (MassHealth). Dual eligible individuals receive benefits from both programs, and MassHealth often helps cover Medicare premiums, deductibles, and cost-sharing that Medicare does not pay. Massachusetts has special programs like One Care for dual eligible members.',
    definition_es: 'Una persona que califica tanto para Medicare como para Medicaid (MassHealth). Las personas con doble elegibilidad reciben beneficios de ambos programas.',
    category: 'program',
    aliases: ['dual-eligible individual', 'dually eligible', 'Medicare-Medicaid'],
    related_slugs: ['medicare', 'medicaid', 'one-care'],
  },
  {
    slug: 'one-care',
    term_en: 'One Care',
    definition_en: 'A Massachusetts program that integrates MassHealth and Medicare benefits for adults aged 21–64 who are enrolled in both programs. One Care provides coordinated physical health, behavioral health, and long-term services through a single health plan, aiming to simplify care for dual eligible members.',
    definition_es: 'Un programa de Massachusetts que integra los beneficios de MassHealth y Medicare para adultos de 21 a 64 años inscritos en ambos programas.',
    category: 'program',
    aliases: ['OneCare'],
    related_slugs: ['dual-eligible', 'masshealth-standard', 'ltss'],
  },
  {
    slug: 'senior-care-options',
    term_en: 'Senior Care Options',
    definition_en: 'A Massachusetts program (SCO) for MassHealth members age 65 and older who are also enrolled in Medicare. SCO provides integrated care through a health plan that coordinates all Medicare and MassHealth services, including primary care, specialty care, and long-term services and supports.',
    definition_es: 'Un programa de Massachusetts para miembros de MassHealth de 65 años o más que también están inscritos en Medicare, que proporciona atención integrada.',
    category: 'program',
    aliases: ['SCO', 'SCO program'],
    related_slugs: ['dual-eligible', 'medicare', 'ltss'],
  },

  // ── Plan Types ────────────────────────────────────────────────────────────
  {
    slug: 'hmo',
    term_en: 'HMO',
    definition_en: 'A Health Maintenance Organization — a type of health plan that limits coverage to doctors who work for or contract with the HMO. HMOs generally require you to choose a primary care provider (PCP) and get referrals to see specialists. Care received outside the HMO network is usually not covered except in emergencies.',
    definition_es: 'Una Organización para el Mantenimiento de la Salud, un tipo de plan de salud que limita la cobertura a médicos que trabajan con el HMO. Generalmente requiere elegir un médico de atención primaria y obtener referencias para ver especialistas.',
    category: 'insurance',
    aliases: ['Health Maintenance Organization'],
    related_slugs: ['pcp', 'referral', 'in-network'],
  },
  {
    slug: 'ppo',
    term_en: 'PPO',
    definition_en: 'A Preferred Provider Organization — a type of health plan that gives you more flexibility to see doctors outside the network without a referral, though you pay more for out-of-network care. PPOs do not require you to choose a primary care provider.',
    definition_es: 'Una Organización de Proveedores Preferidos, un tipo de plan de salud que le da más flexibilidad para ver médicos fuera de la red sin una derivación, aunque pagará más por atención fuera de la red.',
    category: 'insurance',
    aliases: ['Preferred Provider Organization'],
    related_slugs: ['hmo', 'in-network'],
  },
  {
    slug: 'aco',
    term_en: 'ACO',
    definition_en: 'An Accountable Care Organization — a network of doctors, hospitals, and other health care providers that work together to coordinate care for patients. MassHealth uses ACO models to improve care quality and reduce costs. Members enrolled in a MassHealth ACO receive care coordination support.',
    definition_es: 'Una Organización de Atención Responsable, una red de médicos, hospitales y otros proveedores de atención médica que trabajan juntos para coordinar la atención de los pacientes.',
    category: 'insurance',
    aliases: ['Accountable Care Organization', 'accountable care'],
    related_slugs: ['masshealth-standard', 'care-coordination'],
  },

  // ── Medical / Benefits (continued) ────────────────────────────────────────
  {
    slug: 'medical-necessity',
    term_en: 'Medical Necessity',
    definition_en: 'The standard used by health insurers to decide whether a treatment, test, or service is appropriate and should be covered. A service is considered medically necessary when it is required to diagnose or treat a medical condition according to accepted standards of care. Insurers may deny coverage for services they do not consider medically necessary.',
    definition_es: 'El estándar utilizado por las aseguradoras de salud para decidir si un tratamiento, prueba o servicio es apropiado y debe estar cubierto.',
    category: 'medical',
    aliases: ['medically necessary', 'medical necessity determination'],
    related_slugs: ['prior-authorization', 'appeal'],
  },
  {
    slug: 'pca',
    term_en: 'Personal Care Attendant',
    definition_en: 'A worker hired by a MassHealth member to help with activities of daily living such as bathing, dressing, grooming, eating, and mobility. MassHealth\'s PCA program allows eligible members to hire, train, and manage their own attendants, giving them control over who provides their personal care.',
    definition_es: 'Un trabajador contratado por un miembro de MassHealth para ayudar con actividades de la vida diaria como bañarse, vestirse, arreglarse, comer y movilizarse.',
    category: 'medical',
    aliases: ['PCA', 'personal care assistant', 'home attendant'],
    related_slugs: ['ltss', 'masshealth-standard', 'home-health-care'],
  },
  {
    slug: 'home-health-care',
    term_en: 'Home Health Care',
    definition_en: 'Skilled medical services provided in a patient\'s home, such as nursing care, physical therapy, or wound care, ordered by a doctor. Home health care is different from personal care (help with daily activities) — it involves clinical services delivered at home for people recovering from illness, surgery, or managing a chronic condition.',
    definition_es: 'Servicios médicos especializados proporcionados en el hogar del paciente, como atención de enfermería, terapia física o cuidado de heridas, ordenados por un médico.',
    category: 'medical',
    aliases: ['home health', 'home care', 'visiting nurse'],
    related_slugs: ['pca', 'ltss', 'skilled-nursing-facility'],
  },
  {
    slug: 'skilled-nursing-facility',
    term_en: 'Skilled Nursing Facility',
    definition_en: 'A facility that provides 24-hour nursing care and rehabilitation services for people recovering from illness, injury, or surgery who need more care than can be provided at home. Medicare covers short-term SNF stays following a qualifying hospital admission; MassHealth may cover longer stays for eligible members.',
    definition_es: 'Una instalación que brinda atención de enfermería las 24 horas y servicios de rehabilitación para personas que se recuperan de una enfermedad, lesión o cirugía.',
    category: 'medical',
    aliases: ['SNF', 'nursing home', 'nursing facility', 'rehab facility'],
    related_slugs: ['medicare', 'ltss', 'home-health-care'],
  },
  {
    slug: 'inpatient',
    term_en: 'Inpatient',
    definition_en: 'Care that requires being formally admitted to a hospital and staying overnight or longer. Inpatient care includes surgeries, serious illnesses, and other conditions requiring continuous monitoring. Inpatient stays are typically covered under the hospital (Part A) benefit and have different cost-sharing than outpatient care.',
    definition_es: 'Atención que requiere ser admitido formalmente en un hospital y permanecer una noche o más. Incluye cirugías, enfermedades graves y otras condiciones que requieren monitoreo continuo.',
    category: 'medical',
    aliases: ['inpatient care', 'hospital admission', 'admitted'],
    related_slugs: ['outpatient', 'observation-status', 'deductible'],
  },
  {
    slug: 'outpatient',
    term_en: 'Outpatient',
    definition_en: 'Care received without being admitted to a hospital — including doctor visits, lab tests, same-day surgeries, and emergency room visits where you are not admitted overnight. Outpatient services often have different cost-sharing (copays or coinsurance) than inpatient care.',
    definition_es: 'Atención recibida sin ser admitido en un hospital, incluyendo visitas al médico, análisis de laboratorio, cirugías ambulatorias y visitas a urgencias donde no se queda una noche.',
    category: 'medical',
    aliases: ['outpatient care', 'ambulatory care', 'same-day surgery'],
    related_slugs: ['inpatient', 'copayment', 'coinsurance'],
  },
  {
    slug: 'observation-status',
    term_en: 'Observation Status',
    definition_en: 'A designation used when a hospital keeps you for monitoring but does not formally admit you as an inpatient. Observation status is considered outpatient care, which means different cost-sharing applies and Medicare may not cover a subsequent skilled nursing facility stay. It can be confusing and costly if you expect inpatient coverage.',
    definition_es: 'Una designación utilizada cuando un hospital lo mantiene para monitoreo pero no lo admite formalmente como paciente hospitalizado. Se considera atención ambulatoria, lo que significa que se aplican diferentes costos compartidos.',
    category: 'medical',
    aliases: ['observation stay', 'under observation'],
    related_slugs: ['inpatient', 'skilled-nursing-facility', 'medicare'],
  },
  {
    slug: 'behavioral-health',
    term_en: 'Behavioral Health',
    definition_en: 'An umbrella term covering mental health and substance use disorder services, including therapy, psychiatric care, counseling, and addiction treatment. Under the Mental Health Parity law, health plans must cover behavioral health services at the same level as physical health services.',
    definition_es: 'Un término general que cubre los servicios de salud mental y trastornos por uso de sustancias, incluyendo terapia, atención psiquiátrica, asesoramiento y tratamiento de adicciones.',
    category: 'medical',
    aliases: ['mental health and substance use', 'behavioral health services', 'SUD'],
    related_slugs: ['mental-health-parity', 'substance-use-disorder'],
  },
  {
    slug: 'substance-use-disorder',
    term_en: 'Substance Use Disorder',
    definition_en: 'A medical condition involving the compulsive use of alcohol, drugs, or other substances despite harmful consequences. MassHealth covers a full range of substance use disorder treatment, including detoxification, residential treatment, outpatient programs, and medications such as methadone and buprenorphine (Suboxone).',
    definition_es: 'Una condición médica que involucra el uso compulsivo de alcohol, drogas u otras sustancias a pesar de las consecuencias dañinas. MassHealth cubre una gama completa de tratamientos.',
    category: 'medical',
    aliases: ['SUD', 'addiction', 'drug addiction', 'alcohol use disorder', 'opioid use disorder'],
    related_slugs: ['behavioral-health', 'mental-health-parity'],
  },
  {
    slug: 'care-coordination',
    term_en: 'Care Coordination',
    definition_en: 'The deliberate organization of patient care activities and sharing of information among providers to deliver safe, effective, and efficient care. MassHealth ACO and MCO members often have a care coordinator or care manager who helps navigate the health system, schedule appointments, and connect members to community services.',
    definition_es: 'La organización deliberada de las actividades de atención al paciente y el intercambio de información entre proveedores para brindar una atención segura, efectiva y eficiente.',
    category: 'medical',
    aliases: ['care management', 'case management', 'care manager'],
    related_slugs: ['aco', 'masshealth-standard', 'ltss'],
  },
  {
    slug: 'essential-health-benefits',
    term_en: 'Essential Health Benefits',
    definition_en: 'Ten categories of services that the Affordable Care Act requires most health plans to cover: ambulatory services, emergency services, hospitalization, maternity and newborn care, mental health and substance use disorder services, prescription drugs, rehabilitative services, laboratory services, preventive and wellness services, and pediatric services including dental and vision for children.',
    definition_es: 'Diez categorías de servicios que la Ley del Cuidado de Salud a Bajo Precio requiere que cubran la mayoría de los planes de salud, incluyendo servicios ambulatorios, emergencias, hospitalización, maternidad, salud mental, medicamentos y más.',
    category: 'aca',
    aliases: ['EHB', 'required benefits'],
    related_slugs: ['minimum-essential-coverage', 'preventive-care'],
  },
  {
    slug: 'magi',
    term_en: 'MAGI',
    definition_en: 'Modified Adjusted Gross Income — the income calculation method used to determine eligibility for MassHealth and Marketplace financial assistance. MAGI is based on your federal tax return income with certain adjustments. It is used instead of asset tests for most MassHealth programs and for calculating premium tax credits.',
    definition_es: 'Ingreso Bruto Ajustado Modificado, el método de cálculo de ingresos utilizado para determinar la elegibilidad para MassHealth y la asistencia financiera del Marketplace.',
    category: 'aca',
    aliases: ['Modified Adjusted Gross Income', 'MAGI income'],
    related_slugs: ['fpl', 'aptc', 'masshealth-standard'],
  },
  {
    slug: 'navigator',
    term_en: 'Navigator',
    definition_en: 'A trained, certified professional who helps consumers understand their health coverage options and enroll in health insurance through the Massachusetts Health Connector or MassHealth. Navigators provide free, unbiased assistance and can help with applications, renewals, and appeals. Also called Certified Application Counselors (CACs).',
    definition_es: 'Un profesional capacitado y certificado que ayuda a los consumidores a comprender sus opciones de cobertura de salud e inscribirse en el seguro de salud. Los navegadores brindan asistencia gratuita e imparcial.',
    category: 'aca',
    aliases: ['certified application counselor', 'CAC', 'enrollment assister', 'health navigator'],
    related_slugs: ['health-insurance-marketplace', 'masshealth-standard'],
  },
  {
    slug: 'grace-period',
    term_en: 'Grace Period',
    definition_en: 'A set period of time after a premium payment due date during which your health coverage remains active even if you have not paid. For Marketplace plans with premium tax credits, the grace period is 90 days. If you do not pay by the end of the grace period, your coverage may be cancelled.',
    definition_es: 'Un período de tiempo establecido después de la fecha de vencimiento del pago de la prima durante el cual su cobertura de salud permanece activa incluso si no ha pagado.',
    category: 'insurance',
    aliases: ['grace period for payment'],
    related_slugs: ['premium', 'aptc'],
  },
  {
    slug: 'allowed-amount',
    term_en: 'Allowed Amount',
    definition_en: 'The maximum amount a health plan will pay for a covered health care service, also called the "eligible expense," "payment allowance," or "negotiated rate." If your provider charges more than the allowed amount, you may owe the difference — this is called balance billing, and in-network providers agree not to balance bill.',
    definition_es: 'El monto máximo que un plan de salud pagará por un servicio de atención médica cubierto, también llamado "tarifa negociada". Si su proveedor cobra más, puede deber la diferencia.',
    category: 'insurance',
    aliases: ['negotiated rate', 'eligible expense', 'payment allowance'],
    related_slugs: ['balance-billing', 'in-network', 'eob'],
  },
  {
    slug: 'balance-billing',
    term_en: 'Balance Billing',
    definition_en: 'When an out-of-network provider bills you for the difference between their charge and what your insurance paid. For example, if a provider charges $500 and your insurance pays $300, the provider may bill you the remaining $200. In-network providers have agreed to accept the allowed amount and cannot balance bill you. Federal law (No Surprises Act) bans most surprise balance bills.',
    definition_es: 'Cuando un proveedor fuera de la red le factura la diferencia entre su cargo y lo que pagó su seguro. Los proveedores dentro de la red han acordado aceptar el monto permitido y no pueden facturarle la diferencia.',
    category: 'insurance',
    aliases: ['surprise billing', 'surprise bill', 'balance bill'],
    related_slugs: ['allowed-amount', 'in-network', 'out-of-pocket-maximum'],
  },
  {
    slug: 'hdhp',
    term_en: 'High Deductible Health Plan',
    definition_en: 'A health plan with a higher deductible than traditional insurance plans. HDHPs have lower monthly premiums but you pay more out-of-pocket before coverage kicks in. They are often paired with a Health Savings Account (HSA). The IRS sets minimum deductible thresholds to qualify as an HDHP each year.',
    definition_es: 'Un plan de salud con un deducible más alto que los planes de seguro tradicionales. Los HDHP tienen primas mensuales más bajas pero usted paga más de su bolsillo antes de que entre en vigor la cobertura.',
    category: 'insurance',
    aliases: ['HDHP', 'high-deductible plan', 'high deductible plan'],
    related_slugs: ['hsa', 'deductible', 'out-of-pocket-maximum'],
  },
  {
    slug: 'hsa',
    term_en: 'Health Savings Account',
    definition_en: 'A tax-advantaged savings account available to people enrolled in a High Deductible Health Plan (HDHP). You can use HSA funds tax-free to pay for qualified medical expenses including deductibles, copayments, and coinsurance. Unused funds roll over year to year and the account belongs to you even if you change jobs.',
    definition_es: 'Una cuenta de ahorro con ventajas fiscales disponible para personas inscritas en un plan de salud con deducible alto. Puede usar los fondos libres de impuestos para pagar gastos médicos calificados.',
    category: 'insurance',
    aliases: ['HSA', 'health savings'],
    related_slugs: ['hdhp', 'deductible', 'fsa'],
  },
  {
    slug: 'fsa',
    term_en: 'Flexible Spending Account',
    definition_en: 'A special employer-sponsored account that lets you set aside pre-tax dollars to pay for eligible health care expenses like copays, deductibles, dental, and vision care. Unlike an HSA, FSA funds generally must be used within the plan year — unused amounts are forfeited ("use it or lose it"). FSAs are not available with MassHealth but may be offered alongside employer insurance.',
    definition_es: 'Una cuenta especial patrocinada por el empleador que le permite reservar dólares antes de impuestos para pagar gastos de atención médica elegibles. A diferencia de una HSA, los fondos de FSA generalmente deben usarse dentro del año del plan.',
    category: 'insurance',
    aliases: ['FSA', 'flex spending account', 'flexible spending'],
    related_slugs: ['hsa', 'copayment', 'deductible'],
  },
  {
    slug: 'urgent-care',
    term_en: 'Urgent Care',
    definition_en: 'Medical care for conditions that are not life-threatening but need attention within hours — such as minor injuries, infections, or flu symptoms — when your primary care provider is unavailable. Urgent care centers are faster and less expensive than emergency rooms for non-emergencies. Most health plans cover urgent care visits with a copayment.',
    definition_es: 'Atención médica para condiciones que no son potencialmente mortales pero que necesitan atención dentro de horas, como lesiones menores, infecciones o síntomas de gripe. Es más rápido y menos costoso que la sala de emergencias.',
    category: 'medical',
    aliases: ['urgent care center', 'walk-in clinic', 'immediate care'],
    related_slugs: ['emergency-care', 'pcp', 'copayment'],
  },
  {
    slug: 'network-adequacy',
    term_en: 'Network Adequacy',
    definition_en: 'The requirement that a health plan must have a sufficient number of in-network providers — including primary care doctors, specialists, and hospitals — so that members can access care without unreasonable delays or travel. If a plan cannot provide timely access to an in-network provider, it must cover out-of-network care at in-network cost-sharing.',
    definition_es: 'El requisito de que un plan de salud debe tener un número suficiente de proveedores dentro de la red para que los miembros puedan acceder a la atención sin retrasos o viajes irrazonables.',
    category: 'insurance',
    aliases: ['network sufficiency', 'provider network adequacy'],
    related_slugs: ['in-network', 'referral'],
  },
  {
    slug: 'continuity-of-care',
    term_en: 'Continuity of Care',
    definition_en: 'The right to continue receiving care from a current provider for a period of time after your health plan changes or your provider leaves the network. For example, if you are in active treatment for a serious condition and your doctor leaves your plan\'s network, you may have the right to continue seeing that doctor at in-network rates during the transition.',
    definition_es: 'El derecho a continuar recibiendo atención de un proveedor actual por un período de tiempo después de que cambie su plan de salud o su proveedor abandone la red.',
    category: 'medical',
    aliases: ['continuity of treatment', 'care continuity'],
    related_slugs: ['in-network', 'referral', 'pcp'],
  },
  {
    slug: 'dependent',
    term_en: 'Dependent',
    definition_en: 'A person who relies on another for financial support and is covered under that person\'s health insurance plan. Dependents typically include spouses and children. Under the ACA, young adults can stay on a parent\'s health plan until age 26. For MassHealth, household members who meet income and residency requirements can also be covered.',
    definition_es: 'Una persona que depende de otra para apoyo financiero y está cubierta bajo el plan de seguro de salud de esa persona. Los dependientes generalmente incluyen cónyuges e hijos.',
    category: 'aca',
    aliases: ['covered dependent', 'family member coverage'],
    related_slugs: ['open-enrollment', 'qualifying-life-event'],
  },
  {
    slug: 'claims',
    term_en: 'Claim',
    definition_en: 'A request for payment submitted to your health insurance company by you or your health care provider after you receive medical services. The insurer reviews the claim and pays the covered amount to the provider (or reimburses you if you paid out-of-pocket). You receive an Explanation of Benefits (EOB) summarizing how the claim was processed.',
    definition_es: 'Una solicitud de pago presentada a su compañía de seguro de salud por usted o su proveedor de atención médica después de recibir servicios médicos.',
    category: 'insurance',
    aliases: ['insurance claim', 'medical claim', 'claim submission'],
    related_slugs: ['eob', 'prior-authorization'],
  },
  {
    slug: 'waiting-period',
    term_en: 'Waiting Period',
    definition_en: 'The time between when you become eligible for health insurance coverage and when your coverage actually starts. Under the ACA, employer waiting periods cannot exceed 90 days. MassHealth generally does not have a waiting period for eligible applicants, and coverage may be retroactive.',
    definition_es: 'El tiempo entre cuando se vuelve elegible para la cobertura de seguro de salud y cuando su cobertura realmente comienza.',
    category: 'insurance',
    aliases: ['enrollment waiting period'],
    related_slugs: ['retroactive-coverage', 'open-enrollment'],
  },
]
